name: Production
on:
  pull_request:
    branches: ["develop", "master", "main"]
  push:
    ##
    # DO NOT FORGET TO UPDATE THE "if" STATEMENTS BELOW!
    ##
    tags: ["*"]
    branches: ["develop"]

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init gitleaks
        run: |
          wget ${{ vars.GITLEAKS_URL }}
          tar -zxvf ${{ vars.GITLEAKS_FILENAME }} -C /tmp/
          sudo mv /tmp/gitleaks /usr/local/bin/
      - name: gitleaks
        run: |
          gitleaks detect  -v --redact --no-git
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check tag base
        id: check-base
        env:
          branch: master
        run: |
          if   [[ '${{ github.event_name }}' == 'push' ]]; then
            MESSAGE=$(echo $(git log --format=%B -n 1 HEAD))
          elif [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            MESSAGE=$(echo $(git log --format=%B -n 1 HEAD^2))
          fi
          echo "COMMIT_MESSAGE=$(echo "$MESSAGE" | head -n 1 | sed 's/"/\\"/g')" >> $GITHUB_OUTPUT
          echo "commit message is $MESSAGE"
          echo "github-sha is ${{ github.sha }}"
          echo "`git branch -l`"

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
      - uses: olegtarasov/get-tag@v2.1
        id: tag-name
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Build and publish preview image
        uses: docker/build-push-action@v3
        if: "contains(steps.check-base.outputs.COMMIT_MESSAGE, '[build preview]') && !startsWith(github.ref, 'refs/tags/')"
        with:
          context: .
          push: true
          tags: quay.io/subscan-explorer/chatroom:preview-${{ env.SHA }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and publish tag docker image
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: quay.io/subscan-explorer/chatroom:${{ env.GIT_TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
  
      - name: Build and publish sha docker image
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/') == false && github.ref == 'refs/heads/develop'
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: quay.io/subscan-explorer/chatroom:sha-${{ env.SHA }}-${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
